[theme]
base = "dark"
primaryColor = "#00d4ff"  # Ciano neon igual das imagens
backgroundColor = "#0f0f16"  # Grafite muito escuro
secondaryBackgroundColor = "#1a1a24"  # Cor dos painéis laterais
textColor = "#e0e0e0"
font = "sans serif"

[server]
headless = true